### PR TITLE
Fixes issue #797 The back arrow on the top app bar doesn't work when …

### PR DESCRIPTION
**Pull request by rayauf**
The back arrow now appears and works (return to previous Note Detail) also add a UI Test for the solution, please let me now if something missing.

### CODE REVIEW

**Comment by federicoiosue** [comment]
Grat job it works fine and code coverage is ok too!

**Comment by rayauf** [comment]
Hi man sorry for the late response, thanks for the comment it's actually my first contribution to opensource so I really apretiate it, hope to help on another issue on the future. 
Greetings.

**Comment by federicoiosue** [comment]
This partially closes also #798. 
The only misbehavior that is still there is that the when you come back to note from tag opening you have the navigation/burger icon instead than back arrow.
Schermata 2020-12-29 alle 07 42 49

**Comment by rayauf** [comment]
Hi, I looked for the issue and it's showing the back arrow instead of burguer so, I pull the new changes to test with the last version of develop, but I'm having an error: mainActivity.getSketchUri() is not implemented, I commented that part just to Test and it seems fine, any particular way to replicate the bug?

https://user-images.githubusercontent.com/53201300/103573313-a7f5e080-4e93-11eb-8f55-979e4651ba79.mp4

**Comment by federicoiosue** [comment]
Fresh install of the latest changes from develop branch on emulator:
https://user-images.githubusercontent.com/487104/105022189-c2aa8680-5a49-11eb-837b-00180b019bd0.mp4

**Pull request merged**
