### PR TITLE
Fix crash while switching to reduced note layout 

### PR DESCRIPTION
**Pull request by tappdesign**
Expanded note layout was always created, independent from setting

### CODE REVIEW

**Comment by federicoiosue** [comment]
Great job, would you also be able to add a test to check that?
An UI Espresso test would be enough!

**Comment by federicoiosue** [comment]
Great job, would you also be able to add a test to check that?
An UI Espresso test would be enough!

**Comment by tappdesign** [comment]
OK, I will try it, but I have no experience with UI Espresso at all ;-)

**Comment by federicoiosue** [comment]
Great job, pull request merged!

**Comment by tappdesign** [comment]
Thank you very much. And of course, Omni-Notes is very nice piece of code ;-)

**Pull request merged**
